#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : QtAwesome
Version  : 0.5.7
Release  : 18
URL      : https://files.pythonhosted.org/packages/17/1e/04835663fe9092bb856ed8ce8251f8ee363a39b313f688ca24a1ebaefa81/QtAwesome-0.5.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/17/1e/04835663fe9092bb856ed8ce8251f8ee363a39b313f688ca24a1ebaefa81/QtAwesome-0.5.7.tar.gz
Summary  : FontAwesome icons in PyQt and PySide applications
Group    : Development/Tools
License  : MIT
Requires: QtAwesome-license = %{version}-%{release}
Requires: QtAwesome-python = %{version}-%{release}
Requires: QtAwesome-python3 = %{version}-%{release}
Requires: QtPy
Requires: six
BuildRequires : QtPy
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
# QtAwesome
[![license](https://img.shields.io/pypi/l/qtawesome.svg)](./LICENSE)
[![pypi version](https://img.shields.io/pypi/v/qtawesome.svg)](https://pypi.org/project/qtawesome/)
[![conda version](https://img.shields.io/conda/vn/conda-forge/qtawesome.svg)](https://www.anaconda.com/download/)
[![download count](https://img.shields.io/conda/d/conda-forge/qtawesome.svg)](https://www.anaconda.com/download/)
[![OpenCollective Backers](https://opencollective.com/spyder/backers/badge.svg?color=blue)](#backers)
[![Join the chat at https://gitter.im/spyder-ide/public](https://badges.gitter.im/spyder-ide/spyder.svg)](https://gitter.im/spyder-ide/public)<br>
[![PyPI status](https://img.shields.io/pypi/status/qtawesome.svg)](https://github.com/spyder-ide/qtawesome)
[![Appveyor build status](https://ci.appveyor.com/api/projects/status/un8vnw4628cl6qfu?svg=true)](https://ci.appveyor.com/project/spyder-ide/qtawesome)
[![CircleCI build status](https://circleci.com/gh/spyder-ide/qtawesome/tree/master.svg?style=shield)](https://circleci.com/gh/spyder-ide/qtawesome/tree/master)
[![Documentation Status](https://readthedocs.org/projects/qtawesome/badge/?version=latest)](http://qtawesome.readthedocs.org/en/latest/?badge=latest)

%package license
Summary: license components for the QtAwesome package.
Group: Default

%description license
license components for the QtAwesome package.


%package python
Summary: python components for the QtAwesome package.
Group: Default
Requires: QtAwesome-python3 = %{version}-%{release}
Provides: qtawesome-python

%description python
python components for the QtAwesome package.


%package python3
Summary: python3 components for the QtAwesome package.
Group: Default
Requires: python3-core

%description python3
python3 components for the QtAwesome package.


%prep
%setup -q -n QtAwesome-0.5.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552239016
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/QtAwesome
cp LICENSE %{buildroot}/usr/share/package-licenses/QtAwesome/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/QtAwesome/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
